# Generated by Django 3.1.5 on 2021-02-01 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Descrição da peça que está sendo solicitada.', max_length=255, verbose_name='Descrição')),
                ('is_completed', models.BooleanField(default=False, help_text='Status de finalização da entrega.', verbose_name='Status')),
                ('delivery_state', models.CharField(help_text='Estado de entrega.', max_length=255, verbose_name='Estado')),
                ('delivery_city', models.CharField(help_text='Cidade de entrega.', max_length=255, verbose_name='Cidade')),
                ('delivery_street', models.CharField(help_text='Endereço de entrega.', max_length=255, verbose_name='Endereço')),
                ('delivery_number', models.IntegerField(help_text='Número de entrega.', verbose_name='Número')),
                ('delivery_complement', models.CharField(help_text='Complemento de entrega.', max_length=255, verbose_name='Complemento')),
                ('delivery_cep', models.CharField(help_text='CEP de entrega.', max_length=8, verbose_name='CEP')),
                ('delivery_name', models.CharField(help_text='Nome da pessoa que receberá a entrega.', max_length=255, verbose_name='Nome destinatário')),
                ('cellphone', models.CharField(blank=True, default='', help_text='Celular do destinatário para contato.', max_length=15, verbose_name='Celular')),
                ('email', models.CharField(blank=True, default='', help_text='Email do destinatário para contato.', max_length=255, verbose_name='Email')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de criação')),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now, help_text='Data da ultima atualização da demanda.', verbose_name='Data da atualização')),
                ('date_completed', models.DateTimeField(help_text='Data que a demanda foi finalizada.', null=True, verbose_name='Data de finalização')),
                ('user_created', models.ForeignKey(help_text='Criador da demanda.', on_delete=django.db.models.deletion.CASCADE, related_name='demands', to=settings.AUTH_USER_MODEL, verbose_name='Criador')),
                ('user_updated', models.ForeignKey(help_text='Último usuário que atualizou a demanda.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Atualizador')),
            ],
            options={
                'verbose_name': 'Demanda',
                'verbose_name_plural': 'Demandas',
            },
        ),
    ]
