# Generated by Django 3.1.5 on 2021-02-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0002_auto_20210201_1538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demand',
            options={'ordering': ['-date_created'], 'verbose_name': 'Demanda', 'verbose_name_plural': 'Demandas'},
        ),
        migrations.AlterField(
            model_name='demand',
            name='delivery_complement',
            field=models.CharField(blank=True, help_text='Complemento de entrega.', max_length=255, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Status de finalização da entrega.', verbose_name='Finalizada'),
        ),
    ]
