#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python manage.py migrate

# Create initial local user
echo "
from django.contrib.auth import get_user_model;

User = get_user_model();
if not User.objects.filter(username='${USERNAME}').first():
    User.objects.create(username='${USERNAME}', password='${PASSWORD}')
" | python manage.py shell

python manage.py collectstatic --noinput
python manage.py runserver_plus 0.0.0.0:8000

